apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-api-gw-ingress
  namespace: pluto
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "*.wichan.dev"
    secretName: wichan-dev-tls-secret
  rules:
  - host: dev-api-gw.wichan.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dev-api-gw-service
            port:
              number: 8000
